export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';

export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_VIDEOS_ERROR = 'GET_VIDEOS_ERROR';
export const GET_VIDEOS_SUCCESS = 'GET_VIDEOS_SUCCESS';
